---
- name: Save Data ( Database & product file )
  hosts: all
  remote_user: root

  vars_files:
    - ../ansible/vars/vault.yml
    - ../ansible/vars/vars.yml

  vars_prompt:
    #- name: symfony_env
      #prompt: "Enter the environment for your Symfony app (prod|dev|test)"
      #default: prod
      #private: no

  environment:
    SYMFONY_ENV: "prod"
    #SYMFONY_ENV: "{{ symfony_env|lower }}"

  tasks:
    - ping: ~

    - name: apt-get update
      become: true
      apt:
        update_cache: yes

  handlers:
    - name: Restart Nginx
      become: true
      service:
        name: nginx
        state: restarted

    - name: Restart PHP-FPM
      become: true
      service:
        name: php7.3-fpm
        state: restarted
...